"""
BookStore REST API — minimal FastAPI implementation.

Spec:    docs/02-resources.md
Swagger: GET /docs  (auto-generated by FastAPI)
"""

from pathlib import Path
import json
from typing import Optional

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

class Book(BaseModel):
    title: str
    author: str
    category: str


# ---------------------------------------------------------------------------
# App setup
# ---------------------------------------------------------------------------

app = FastAPI(title="BookStore API")

# CORS: allow any origin so any frontend implementation can connect (required by spec)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Flat-file database helpers
# ---------------------------------------------------------------------------

DB = Path("books.json")


def read() -> list[Book]:
    return [Book(**b) for b in json.loads(DB.read_text())]


def write(books: list[Book]) -> None:
    DB.write_text(json.dumps([b.model_dump() for b in books], indent=2))


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

@app.get("/books", response_model=list[Book])
def get_books():
    """Return all books."""
    return read()


@app.post("/books/create_book", response_model=Book, status_code=201)
def create_book(book: Book):
    """Create a new book. Returns the created book with status 201."""
    books = read()
    books.append(book)
    write(books)
    return book


@app.put("/books/update_book", response_model=Optional[Book])
def update_book(updated: Book):
    """Update a book matched by title. Returns the book (200) or null (404)."""
    books = read()
    for i, book in enumerate(books):
        if book.title == updated.title:
            books[i] = updated
            write(books)
            return updated
    return JSONResponse(status_code=404, content=None)


@app.delete("/books/delete_book/{book_title}")
def delete_book(book_title: str):
    """Delete a book by title. Returns 1 (200) on success, 0 (404) if not found."""
    books = read()
    filtered = [b for b in books if b.title != book_title]
    if len(filtered) == len(books):
        return JSONResponse(status_code=404, content=0)
    write(filtered)
    return JSONResponse(status_code=200, content=1)
